name: batesste-advent-smoke-test

on:
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-smoke-test:
    name: ubuntu-smoke-test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code using action/checkout
      uses: actions/checkout@v4.1.1
    - name: Run the ./advent.py program with some simple arguments.
      run: ./advent.py --names Alice,Bob,Charlie,Debora --number 2
